# Honeyshield Advanced Configuration
# ML-First Approach - No Fallbacks

model:
  path: "models/advanced_phishing_detector.pkl"
  retrain_interval_days: 30
  confidence_threshold: 0.7
  feature_engineering: true

analysis:
  approach: "ml_first"
  min_confidence: 0.6
  enable_behavioral_analysis: true
  enable_temporal_analysis: true
  threat_classification: true

monitoring:
  check_interval_hours: 2
  max_messages_per_cycle: 100
  enable_real_time: false  # Set to true for production

linkedin:
  # Note: Actual credentials should be in environment variables
  profiles:
    - name: "Security Researcher"
      industry: "Information Technology"
      experience: "Senior"
    - name: "Business Executive" 
      industry: "Management"
      experience: "Director"

logging:
  level: "INFO"
  file: "logs/honeyshield_advanced.log"
  enable_analysis_logs: true

dashboard:
  refresh_interval: 30
  enable_ml_insights: true
  show_confidence_scores: true
  threat_visualization: true