linkedin:
  email: "your_decoy_email@protonmail.com"
  password: "your_secure_password"
  profile_url: "https://www.linkedin.com/in/your-decoy-profile"

analysis:
  suspicious_keywords:
    - "confidential"
    - "classified"
    - "sensitive"
    - "urgent"
    - "immediate"
    - "offer"
    - "opportunity"
    - "investment"
    - "business proposal"
    - "meet me"
    - "personal number"
    - "WhatsApp"
    - "Telegram"
  
  high_risk_phrases:
    - "government contract"
    - "military project"
    - "defense"
    - "nuclear"
    - "we need to talk privately"
    - "can we move to another app"

scoring:
  keyword_weight: 5
  sentiment_weight: 3
  relationship_escalation_weight: 10
  request_private_info_weight: 15